/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sirsaugsage (https://sketchfab.com/sirsausage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
Title: Fantasy Game Inn
*/

import { RigidBody } from '@react-three/rapier'

export default function Map(props) {

  return (
    <RigidBody type="fixed" colliders="trimesh" ccd {...props}>
      <mesh>
        <boxGeometry args={[10, 1, 10]} />
        <meshStandardMaterial color="orange" />
      </mesh>
    </RigidBody>
  )
}

